with open('1.txt.txt', 'w') as f:
    f.write('hello\n')
    f.write('wwww\nffff\ndddd')
    f.writelines(['1.txt, 2, 3, 4'])

with open('1.txt.txt', 'r') as f:
   result = f.readline()
   print(result)
   print('*' * 100)
   result = f.readline()
   print(result)
   print('*' * 100)
   result = f.readline()
   print(result)
   print('*' * 100)
   result = f.readline()
   print(result)
   print('*' * 100)
   result = f.readline()
   print(result)
   print('*' * 100)
   result = f.readline()
   print(result)
   print('*' * 100)